const industryList = [
    {
        id:1,
        parentId:0,
        title:'工号（含账号)',
        children:[
            {
                id:11,
                parentId:1,
                detail:'目标列名：staffID'
            },
            {
                id:12,
                parentId:1,
                detail:'须检查staffID列工号是否完整'
            },
            {
                id:13,
                parentId:2,
                detail:'每行一个工号，不要带引号'
            },
        ]
    },
    {
        id:2,
        parentId:0,
        title:'员工邮箱',
        children:[
            {
                id:21,
                parentId:2,
                detail:'目标列名：staffMail'
            },
            {
                id:22,
                parentId:2,
                detail:'每行一个邮箱,不要带引号'
            }
        ]
    },
    {
        id:3,
        parentId:0,
        title:'服务器IP',
        children:[
            {
                id:31,
                parentId:3,
                detail:'目标列名：serverIP'
            },
            {
                id:32,
                parentId:3,
                detail:'每行一个IP,不要带引号'
            }
        ]
    },
]
export default industryList