const menuList = [
  {
    title:'首页',
    key:'/home',
    icon:'home',
  },
  {
    title:'商品',
    key:'/products',
    icon:'appstore',
    children:[
      {
        title:'品类管理',
        key:'/category',
        icon:'bars',
      },
      {
        title:'商品管理',
        key:'/product',
        icon:'tool',
      }
    ]
  },
  {
    title:'角色管理',
    key:'/role',
    icon:'safety',
  },
  {
    title:'用户管理',
    key:'/user',
    icon:'user',
  },
 
  {
    title:'图形图表',
    key:'/charts',
    icon:'area-chart',
    children:[
      {
        title:'柱状图',
        key:'/charts/bar',
        icon:'bar-chart',
      },
      {
        title:'折线图',
        key:'/charts/line',
        icon:'line-chart',
      },
      {
        title:'饼状图',
        key:'/charts/pie',
        icon:'pie-chart',
      },
    ]
  },
  {
    title:'工具箱',
    key:'tools',
    icon:'tool',
    children: [
      {
        title:'产业定位',
        key:'/industry',
        icon:'user',
      },
      {
        title:'审批流程',
        key:'/examine',
        icon:'user',
      },
    ]
  },

]
export default menuList